services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: 'gitlab'
    restart: always
    hostname: ${hostname}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${hostname}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/${hostname}.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/${hostname}.key"
        # Container Registry
        registry_external_url 'https://${hostname}:5050'
        registry['enable'] = true
        registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/${hostname}.crt"
        registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/${hostname}.key"
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
      - '5050:5050'
    volumes:
      - ./volumes/config:/etc/gitlab
      - ./volumes/logs:/var/log/gitlab
      - ./volumes/data:/var/opt/gitlab
      - ./volumes/ssl:/etc/gitlab/ssl:ro
