services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: 'gitlab'
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local'
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.local.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.local.key"
        # Container Registry
        registry_external_url 'https://gitlab.local:5050'
        registry['enable'] = true
        registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.local.crt"
        registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.local.key"
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
      - '5050:5050'
    volumes:
      - ./volumes/config:/etc/gitlab
      - ./volumes/logs:/var/log/gitlab
      - ./volumes/data:/var/opt/gitlab
      - ./volumes/ssl:/etc/gitlab/ssl:ro
